"""Packaged in-app documentation for Eshtaya Smart Control."""
from __future__ import annotations

DOCUMENTATION = {
    'ar': {
        'ACCESS_CONTROL': '# مركز الصلاحيات والمستخدمين\n\n## المبدأ\nيستخدم مستخدمي Home Assistant الحاليين ولا ينشئ نظام حسابات منفصلاً. المديرون يمتلكون Full Access دائماً ولا يمكن لقواعد Eshtaya حجبهم.\n\n## الأدوار المدمجة\nNo Access، Viewer، Operator، Technician وPlatform Manager. ويمكن إنشاء أدوار مخصصة.\n\n## الصلاحيات الدقيقة\nDashboard، Entity view/manage، Tuya view/control/configure، Multi-Way view/control/manage، Documentation، System view/actions/reports وAccess management.\n\n## Overrides\nيمكن إضافة Allow أو Deny فوق الدور للمستخدم الواحد. Deny له الأولوية. ويمكن وضع Expiration لصلاحيات مؤقتة.\n\n## Enforcement\nالإخفاء في الواجهة لتحسين UX فقط؛ الحماية الحقيقية تتم في WebSocket Backend. الاستدعاء اليدوي بدون صلاحية يُرفض.\n\n## Audit Log\nيسجل من عدّل صلاحيات من، الوقت، الدور والتغييرات المهمة. لا يسجل كلمات المرور أو Tuya Client Secret.\n\n## حدود النطاق\nالقسم يتحكم بصلاحيات Eshtaya Smart Control. لا يعدّل صلاحيات Core Home Assistant الداخلية ولا يتجاوز نظام مصادقة HA.\n',
        'ARCHITECTURE': '# البنية التقنية\n\n## الطبقات\nConfig Entry واحد، Backend Python، Storage منفصل لكل وحدة، WebSocket APIs، Frontend Web Components وHACS packaging.\n\n## الوحدات\nEntity Control، Tuya Manager، Multi-Way Engine، Smart Groups، Migration Coordinator، Access Control وDocumentation service.\n\n## مبدأ الأمان\nالواجهة لا تُعتبر Trusted boundary. كل العمليات الحساسة تتحقق من المستخدم والصلاحية في Backend.\n',
        'COMMISSIONING': '# Commissioning\n\n## الهدف\nتجهيز الجروب قبل اعتباره Production: اكتشاف الكيانات، اختيار Output/Controllers، اختبار الاتجاه، rapid-toggle test والتحقق من زمن الاستجابة.\n\n## خطوات موصى بها\n1. تأكد أن كل الكيانات Online.\n2. اختبر Output وحده.\n3. أضف Controller واحداً.\n4. اختبر ON/OFF السريع.\n5. أضف الباقي تدريجياً.\n6. راقب Activity وHealth.\n\n## الأمان\nالاختبارات المدمرة أو التي تحرك أجهزة فعلية يجب تشغيلها فقط بوجود شخص في الموقع.\n',
        'DASHBOARD': '# لوحة التحكم\n\n## نظرة عامة\nلوحة التحكم تعرض صحة المنصة، عدد الكيانات غير المتاحة، حالة Alexa files، Multi-Way، Smart Groups، Tuya، الترحيل والتوصيات.\n\n## Health Score\nالدرجة مؤشر تشخيصي وليس بديلاً عن فحص Home Assistant. تتأثر بمشاكل الترحيل، ملفات Alexa غير المتزامنة، الكيانات غير المتاحة والجروبات المتدهورة.\n\n## Smart Recommendations\nالتوصيات تُنشأ محلياً من حالة النظام ولا ترسل أسراراً أو بيانات اعتماد للخارج. افتح القسم المرتبط لمعالجة السبب.\n\n## Quick Actions\nإصلاح ملفات Alexa، تحديث Tuya، مزامنة الجروبات وتنزيل تقرير دعم. الإجراءات التي قد ترسل أوامر فعلية تتطلب تأكيداً.\n',
        'ENTITY_CONTROL': '# إدارة الكيانات وAlexa\n\n## الوظيفة\nإدارة أسماء الكيانات وقواعد ظهورها في Alexa مع فلترة جماعية وForce Allow/Exclude وملفات hidden_entities.\n\n## أوضاع Alexa\nAuto يعتمد على القواعد، Show يفرض الظهور، Hide يفرض الإخفاء.\n\n## ملفات المزامنة\nيتم الحفاظ على `/config/hidden_entities.yaml` و`/config/www/hidden_entities.yaml`. System Center يكشف اختلاف النسختين ويستطيع إعادة توليدهما.\n\n## الصلاحيات\n`entity.view` للمشاهدة و`entity.manage` للتعديل. كل تعديل محمي من الـBackend حتى لو تم استدعاء WebSocket يدوياً.\n\n## الصيانة\nاستخدم Cleanup Orphans بحذر بعد حذف كيانات نهائياً، وراجع Export قبل تعديلات جماعية كبيرة.\n',
        'GETTING_STARTED': '# البدء والتثبيت\n\n## الهدف\nEshtaya Smart Control منصة موحدة لإدارة الكيانات، Alexa، Tuya، Multi-Way، المجموعات الذكية، الترحيل، التشخيص والصلاحيات.\n\n## قبل التثبيت\n1. أنشئ Full Backup من Home Assistant.\n2. لا تحذف إضافات Eshtaya القديمة قبل أول تشغيل إذا كنت تريد الترحيل التلقائي.\n3. حدّث HACS وHome Assistant إلى إصدار متوافق.\n\n## التثبيت\nأضف المستودع إلى HACS كـ Integration، ثبّت الإصدار، أعد تشغيل Home Assistant، ثم أضف Eshtaya Smart Control من Devices & Services. أول Setup لا يطلب بيانات Tuya.\n\n## أول تشغيل\nالمنصة تهيئ Entity Control وMulti-Way وMigration Center وAccess Control. إذا وجدت إضافات قديمة يتم أخذ نسخة احتياطية ثم نقل الإعدادات والتحقق منها.\n\n## Tuya\nTuya اختيارية. افتح قسم Tuya وأدخل Region وClient ID وClient Secret وUID ثم اختبر الاتصال قبل التفعيل.\n\n## بعد التثبيت\nراجع System Center، Migration Center، Multi-Way health، ثم Access Control لتحديد صلاحيات المستخدمين غير المديرين.\n',
        'MIGRATION': '# Migration Center\n\n## التسلسل\nDetect → Backup → Copy → Quiesce Legacy → Start Runtime → Validate → Remove Legacy Entries → Reconcile → HACS Cleanup.\n\n## الأمان\nلا يتم حذف Config Entries القديمة قبل نجاح Validation. عند الفشل تُجرى محاولة Rollback وتظل نسخة الهجرة محفوظة.\n\n## Multi-Way\nالمحرك القديم والجديد لا يجب أن يتحكما بنفس الجروبات معاً. المنصة توقف القديم قبل تشغيل الجديد.\n\n## التقرير\nيمكن تنزيل Migration Report بدون أسرار Tuya أو Raw backup payload.\n',
        'MULTIWAY': '# Multi-Way Control\n\n## المفهوم\nيربط خرجاً فعلياً بعدة Controllers مع مزامنة آمنة ومنع feedback loops ودعم Mirror/Toggle/Follow وPerformance modes.\n\n## حماية الإقلاع في v2.1\nبعد Restart لا تعتبر المنصة غياب State دليلاً على حذف الكيان. يتم تأخير Repairs أثناء Startup Protection، وفحص Entity Registry أيضاً. هذا يمنع تحذيرات كاذبة أثناء تحميل Tuya أو تكاملات Cloud البطيئة.\n\n## Missing Entity الحقيقي\nيُنشأ Repair فقط عندما لا يكون الكيان موجوداً في State Machine ولا Entity Registry بعد انتهاء حماية الإقلاع.\n\n## الصحة\nHealthy، Degraded، Out of Sync، Recovering، Missing Output وDisabled. استخدم Diagnostics وActivity لفهم المصدر.\n\n## الصلاحيات\n`multi.view` للمشاهدة، `multi.control` للمزامنة والاختبارات والأوامر، `multi.manage` للإنشاء والتعديل والحذف والنسخ والاستيراد.\n',
        'SECURITY_BACKUP': '# الأمان والنسخ الاحتياطي\n\n## الأسرار\nTuya Client Secret يبقى في Config Entry ولا يُعرض في التقارير أو حالة الواجهة.\n\n## النسخ الاحتياطي\nاعمل Full HA Backup قبل التحديثات الكبيرة، وقبل Bulk Import أو Migration. Multi-Way يوفر Export/Full Backup إضافي.\n\n## الصلاحيات\nاستخدم Least Privilege: Viewer للمشاهدة، Operator للتحكم، Technician للصيانة. لا تمنح configure/manage إلا عند الحاجة.\n\n## التقارير\nراجع التقرير قبل مشاركته، رغم أن النظام يستبعد الأسرار المعروفة تلقائياً.\n',
        'SMART_GROUPS': '# Smart Groups\n\n## الأنواع\nPhysical Controller Groups، Virtual Aggregate Groups وAction Groups.\n\n## سياسات الحالة\nANY/ALL تحدد كيف تُستنتج الحالة، وBidirectional يحدد هل تغيرات الأعضاء تعيد مزامنة المجموعة.\n\n## Reliability\nتوجد Command Echo Guards، Quarantine، Quality/Latency diagnostics، Failure policies وUndo/Backup.\n\n## الاستخدام\nابدأ بجروب صغير، اختبره، ثم فعّل مزامنة أوسع. راقب Diagnostics بعد إضافة أجهزة Cloud.\n',
        'SYSTEM_CENTER': '# System Center\n\n## الوظيفة\nمركز الصحة والتوصيات والإجراءات والتقارير والترحيل.\n\n## التقارير\nSystem Report مخصص للدعم ولا يتضمن Tuya Client Secret أو access tokens أو Raw migration storage.\n\n## الإجراءات\nRepair Alexa Files، Refresh Tuya، Sync Groups وRefresh All. بعض الإجراءات تتطلب `system.actions`. تنزيل التقارير يتطلب `system.reports`.\n\n## التوصيات\nتعامل معها حسب Severity: Critical أولاً ثم Warning. Informational لا تخفض الصحة دائماً.\n',
        'TROUBLESHOOTING': '# حل المشاكل\n\n## Documentation 404\nمن v2.1 يتم تحميل التوثيق عبر WebSocket من ملفات داخل مجلد الـIntegration، لذلك لا يعتمد على `/docs` في Static frontend. إذا استمر الخطأ أعد تشغيل Home Assistant وتأكد أن HACS ثبت كل ملفات الإصدار.\n\n## Multi-Way missing بعد Restart\nإذا اختفى التحذير بعد دقائق كان سببه تحميل Integration بطيء. v2.1 يفحص Entity Registry ويؤجل Repair أثناء Startup Protection. إذا استمر بعد استقرار النظام، افحص Entity ID وهل حُذف من Registry فعلاً.\n\n## Access denied\nالمدير افتح Access Control وحدد Role للمستخدم. المستخدم غير المدير بدون Assignment يأخذ No Access افتراضياً.\n\n## Tuya\nاستخدم Test Config، تحقق من Region/UID وصلاحيات Tuya Cloud project.\n\n## UI قديم بعد Update\nاعمل Hard Refresh للمتصفح بعد Restart لأن ملفات Frontend versioned لكن بعض المتصفحات قد تحتفظ بنسخة مؤقتة.\n',
        'TUYA_CONTROL': '# إدارة Tuya\n\n## التفعيل\nTuya ليست مطلوبة أثناء تثبيت Eshtaya Smart Control. أول دخول لقسم Tuya يعرض نموذج التفعيل إذا لم توجد بيانات محفوظة.\n\n## البيانات المطلوبة\nRegion/Endpoint، Client ID، Client Secret وUID. الـClient Secret لا يُعاد إلى الواجهة بعد حفظه.\n\n## Test & Activate\nاختبر بيانات الاعتماد أولاً. عند نجاح الاختبار تُحفظ في Config Entry ويُفعّل القسم. يمكن التعديل أو إلغاء التفعيل لاحقاً.\n\n## إدارة الأجهزة\nيعرض القسم الأجهزة، التفاصيل، Shadow properties، تغيير أسماء الأجهزة والخصائص والتعديلات الجماعية.\n\n## الصلاحيات\n`tuya.view` للمشاهدة، `tuya.control` لتغييرات الأجهزة، و`tuya.configure` لإدارة بيانات الاعتماد.\n',
    },
    'en': {
        'ACCESS_CONTROL': '# Access Control Center\n\nUses existing Home Assistant users. Administrators always retain full platform access. Built-in roles include No Access, Viewer, Operator, Technician and Platform Manager. Granular permissions cover modules and actions, with per-user allow/deny overrides, optional expiry and an audit log. Enforcement occurs in the WebSocket backend, not only in the UI. This controls Eshtaya Smart Control permissions and does not bypass Home Assistant core authorization.\n',
        'ARCHITECTURE': '# Architecture\n\nSingle config entry, Python backend managers, versioned storage, WebSocket APIs, Web Component frontend and HACS packaging. Sensitive operations are authorized in the backend because the frontend is not a security boundary.\n',
        'COMMISSIONING': '# Commissioning\n\nCommission groups progressively: verify entities online, test the output, add one controller, run rapid-toggle testing, then add remaining controllers. Review Activity and Diagnostics before production use.\n',
        'DASHBOARD': '# Dashboard\n\nThe Dashboard provides health score, entity availability, Alexa file synchronization, Multi-Way and Smart Group status, Tuya activation and smart recommendations. Quick actions are permission-protected and physical actions require explicit confirmation.\n',
        'ENTITY_CONTROL': '# Entity & Alexa Control\n\nManage entity display names and Alexa exposure rules. Auto follows rules, Show forces exposure and Hide forces exclusion. The integration keeps both hidden entity YAML copies synchronized and provides repair/orphan maintenance. Permissions: `entity.view` and `entity.manage`.\n',
        'GETTING_STARTED': '# Getting Started\n\n## Purpose\nEshtaya Smart Control unifies Entity/Alexa management, optional Tuya Cloud, Multi-Way, Smart Groups, migration, diagnostics and access control.\n\n## Installation\nCreate a full Home Assistant backup, install the repository through HACS, restart Home Assistant and add the integration. Tuya credentials are not requested during first setup. Configure Tuya later from its dashboard when required.\n\n## First run\nThe platform initializes storage, migration, Multi-Way and access control. Legacy Eshtaya integrations are backed up, copied, validated and only then removed.\n',
        'MIGRATION': '# Migration Center\n\nDetect → Backup → Copy → Quiesce legacy → Start runtime → Validate → Remove legacy entries → Reconcile → HACS cleanup. Legacy entries are not removed before validation succeeds; rollback is attempted on failure.\n',
        'MULTIWAY': '# Multi-Way Control\n\nMulti-Way links one output to multiple controllers with loop prevention, ordered edge processing and health diagnostics. v2.1 suppresses false missing-entity repairs during startup and considers the Home Assistant Entity Registry before declaring an entity deleted. Permissions: view/control/manage.\n',
        'SECURITY_BACKUP': '# Security & Backup\n\nKeep a full Home Assistant backup before major upgrades and imports. Tuya Client Secret and access tokens are excluded from support reports. Apply least privilege when assigning platform roles.\n',
        'SMART_GROUPS': '# Smart Groups\n\nSupports physical-controller, virtual aggregate and action groups with state policies, bidirectional synchronization, command-echo protection, quarantine, diagnostics, templates and backup/undo.\n',
        'SYSTEM_CENTER': '# System Center\n\nCentral health, recommendations, safe maintenance actions and sanitized support reports. `system.actions` protects maintenance commands; `system.reports` protects report downloads.\n',
        'TROUBLESHOOTING': '# Troubleshooting\n\n## Documentation 404\nv2.1 serves packaged documentation through the integration WebSocket API instead of a fragile frontend static path. Restart Home Assistant after updating.\n\n## False Multi-Way missing entity after restart\nv2.1 delays repairs during startup and checks the Entity Registry. Persistent warnings after the system is fully loaded should be investigated as real entity removals.\n\n## Access denied\nAn administrator must assign a role. Non-admin users default to No Access.\n',
        'TUYA_CONTROL': '# Tuya Control\n\nTuya is optional and activated inside the dashboard. Test credentials before activation. Client Secret is not returned to the frontend after storage. Permissions are split into `tuya.view`, `tuya.control` and `tuya.configure`.\n',
    },
}

def get_document(language: str, slug: str) -> str | None:
    return DOCUMENTATION.get(language, {}).get(slug)
