sync_group:
  fields:
    group_id:
      required: true
      selector:
        text:

sync_all:

enable_group:
  fields:
    group_id:
      required: true
      selector:
        text:

disable_group:
  fields:
    group_id:
      required: true
      selector:
        text:

set_group_state:
  fields:
    group_id:
      required: true
      selector:
        text:
    state:
      required: true
      selector:
        select:
          translation_key: group_state
          options:
            - "on"
            - "off"

test_group:
  fields:
    group_id:
      required: true
      selector:
        text:

set_smart_group_state:
  fields:
    group_id:
      required: true
      selector:
        text:
    state:
      required: true
      selector:
        select:
          translation_key: group_state
          options:
            - "on"
            - "off"

sync_smart_group:
  fields:
    group_id:
      required: true
      selector:
        text:

test_smart_group:
  fields:
    group_id:
      required: true
      selector:
        text:

run_smart_group:
  fields:
    group_id:
      required: true
      selector:
        text:

template_scan:

template_create:
  fields:
    source_entity:
      required: true
      selector:
        entity:
          domain: switch
    template_type:
      required: true
      selector:
        select:
          options:
            - light
            - fan
    name:
      required: true
      selector:
        text:
    entity_id:
      required: true
      selector:
        text:

template_edit:
  fields:
    managed_entity:
      required: true
      selector:
        entity:
          domain:
            - light
            - fan
    name:
      required: true
      selector:
        text:
    entity_id:
      required: true
      selector:
        text:

template_delete:
  fields:
    managed_entity:
      required: true
      selector:
        entity:
          domain:
            - light
            - fan

template_relink:
  fields:
    managed_entity:
      required: true
      selector:
        entity:
          domain:
            - light
            - fan
    source_entity:
      required: true
      selector:
        entity:
          domain: switch
